### PR TITLE
Add basic language server

### PR DESCRIPTION
**Pull request by matthewpi**

### CODE REVIEW

**Comment by francislavoie** [comment]
😮 this is sweet!

Before you spend too much time on this, make sure to take a look at the updated global options docs here, which will be pushed with v2.3 very soon: https://github.com/caddyserver/website/blob/master/src/docs/markdown/caddyfile/options.md

**Comment by matthewpi** [comment]
> 😮 this is sweet!
> 
> Before you spend too much time on this, make sure to take a look at the updated global options docs here, which will be pushed with v2.3 very soon: https://github.com/caddyserver/website/blob/master/src/docs/markdown/caddyfile/options.md
> 
> Edit: lol you clicked merge before I got the chance to submit my comment 😅

Haha, all good.  I'll take look into that 👍

**Comment by mholt** [comment]
Ooo wow! I can't wait to try this.

I hope you're able to automatically render/update the docs for this, somehow? We don't really have a good structured definition of the Caddyfile for programmable purposes...

**Comment by matthewpi** [comment]
> Ooo wow! I can't wait to try this.
> 
> I hope you're able to automatically render/update the docs for this, somehow? We don't really have a good structured definition of the Caddyfile for programmable purposes...

My goal was to get a basic language server integrated, if you haven't seen already the code is a mess.  I should probably write some code to generate the documentation from the docs so it can be easily updated.  I'm still trying to figure out the best way to handle certain things such as suggestions for directives as some can only appear under a certain scope, and how to handle extensions that register global options or new directives.

**Pull request merged**
